window.SONGS = [
"Highway Tune Greta Van Fleet",
"Safari Song Greta Van Fleet",
"When The Curtain Falls Greta Van Fleet",
"Heat Above Greta Van Fleet",
"Pressure and Time Rival Sons",
"Open My Eyes Rival Sons",
"Do Your Worst Rival Sons",
"Electric Man Rival Sons",
"When I'm Gone Dirty Honey",
"Rolling 7s Dirty Honey",
"California Dreamin' Dirty Honey",
"Gypsy Dirty Honey",
"Could Have Been Me The Struts",
"Body Talks The Struts",
"Kiss This The Struts",
"Put Your Money on Me The Struts",
"Joker & The Thief Wolfmother",
"Woman Wolfmother",
"Vagabond Wolfmother",
"Dimension Wolfmother",
"CHOKE The Warning",
"MORE The Warning",
"DISCIPLE The Warning",
"EVOLVE The Warning",
"Way Down We Go Kaleo",
"No Good Kaleo",
"Break My Baby Kaleo",
"Glass House Kaleo",
"Figure It Out Royal Blood",
"Out of the Black Royal Blood",
"Little Monster Royal Blood",
"Lights Out Royal Blood",
"In My Mind The Amazons",
"Mother The Amazons",
"Doubt It The Amazons",
"Future Dust The Amazons",
"Flawless Dorothy",
"Raise Hell Dorothy",
"Gun In My Hand Dorothy",
"Rest in Peace Dorothy",
"Colors Black Pumas",
"Fire Black Pumas",
"Oct 33 Black Pumas",
"Blues Hand Me Down Vintage Trouble",
"Run Like The River Vintage Trouble",
"Nobody Told Me Vintage Trouble",
"Gracefully Vintage Trouble",
"On to the Next Tyler Bryant & The Shakedown",
"Shock & Awe Tyler Bryant & The Shakedown",
"Drive Me Mad Tyler Bryant & The Shakedown",
"Lipstick Wonder Woman Tyler Bryant & The Shakedown",
"Oh No Goodbye June",
"Charge Up The Power Goodbye June",
"Man of the Moment Goodbye June",
"Live In The Now Goodbye June",
"Sweet Mountain River Monster Truck",
"Don't Tell Me How to Live Monster Truck",
"For the Sun Monster Truck",
"The Enforcer Monster Truck",
"High Class Woman Blues Pills",
"Lady in Gold Blues Pills",
"Little Sun Blues Pills",
"Black Smoke Blues Pills",
"Temptation The Tea Party",
"The Bazaar The Tea Party",
"Sister Awake The Tea Party",
"Heaven Coming Down The Tea Party",
"Get It On Kingdom Come",
"What Love Can Be Kingdom Come",
"Pushin' Hard Kingdom Come",
"Whole Lotta Love Led Zeppelin",
"Black Dog Led Zeppelin",
"Immigrant Song Led Zeppelin",
"No Quarter Led Zeppelin",
"Sweet Emotion Aerosmith",
"Mama Kin Aerosmith",
"Dream On Aerosmith",
"Highway Star Deep Purple",
"Child In Time Deep Purple",
"Smoke on the Water Deep Purple",
"Can't Get Enough Bad Company",
"Feel Like Makin' Love Bad Company",
"All Right Now Free",
"Fortunate Son CCR",
"Proud Mary CCR",
"Riders on the Storm The Doors",
"Break On Through The Doors"
];
